version: '3.6'

services:
  db:
    image: postgres:13-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=serp
      - POSTGRES_PASSWORD=Temp1234
    volumes:
      - pgdata:/var/lib/postgresql/data/

  web:
    build: .
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./app/:/app/src/

volumes:
    pgdata:
