# Generated by Django 3.1.4 on 2020-12-14 21:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('results', models.IntegerField()),
                ('most_common_words', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default=list, size=None)),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Resusult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('link', models.URLField()),
                ('order', models.PositiveSmallIntegerField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='serp.searchrequest')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
